#===Dependents for eurosys18.tex:
out/eurosys18.pdf dep.mk :\
    /usr/local/texlive/2017/texmf-dist/fonts/map/fontname/texfonts.map\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/adobe/zapfding/pzdr.tfm\
    /usr/local/texlive/2017/texmf-dist/tex/generic/ifxetex/ifxetex.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/gettitlestring.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/se-ascii-print.def\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/stringenc.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/xkeyval/keyval.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/xkeyval/xkeyval.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/xkeyval/xkvutils.tex\
    /usr/local/texlive/2017/texmf-dist/tex/latex/amsmath/amsgen.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/base/article.cls\
    /usr/local/texlive/2017/texmf-dist/tex/latex/base/ifthen.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/base/size10.clo\
    /usr/local/texlive/2017/texmf-dist/tex/latex/datetime/datetime-defaults.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/datetime/datetime.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/etoolbox/etoolbox.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/fmtcount/fc-english.def\
    /usr/local/texlive/2017/texmf-dist/tex/latex/fmtcount/fcnumparser.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/fmtcount/fcprefix.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/fmtcount/fmtcount.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/hyperref/hxetex.def\
    /usr/local/texlive/2017/texmf-dist/tex/latex/hyperref/hyperref.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/hyperref/nameref.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/hyperref/pd1enc.def\
    /usr/local/texlive/2017/texmf-dist/tex/latex/hyperref/puenc.def\
    /usr/local/texlive/2017/texmf-dist/tex/latex/latexconfig/hyperref.cfg\
    /usr/local/texlive/2017/texmf-dist/tex/latex/natbib/natbib.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/oberdiek/auxhook.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/oberdiek/kvoptions.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/polyglossia/gloss-english.ldf\
    /usr/local/texlive/2017/texmf-dist/tex/latex/polyglossia/gloss-french.ldf\
    /usr/local/texlive/2017/texmf-dist/tex/latex/polyglossia/gloss-german.ldf\
    /usr/local/texlive/2017/texmf-dist/tex/latex/polyglossia/gloss-italian.ldf\
    /usr/local/texlive/2017/texmf-dist/tex/latex/polyglossia/gloss-portuges.ldf\
    /usr/local/texlive/2017/texmf-dist/tex/latex/polyglossia/gloss-spanish.ldf\
    /usr/local/texlive/2017/texmf-dist/tex/latex/psnfss/times.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/url/url.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/xkeyval/xkeyval.sty\
    /usr/local/texlive/2017/texmf-dist/web2c/texmf.cnf\
    /usr/local/texlive/2017/texmf-var/web2c/xetex/xelatex.fmt\
    /usr/local/texlive/2017/texmf.cnf\
    abstract.tex\
    analysis.tex\
    design_and_implementation.tex\
    eurosys18.tex\
    instrumentation.tex\
    introduction.tex\
    sigplanconf-eurosys.cls
#===End dependents for eurosys18.tex:
