#include "loader.hpp"
namespace LoadData
{
	const map<string, uint64_t> op_code_map = {
		make_pair("MACH_IPC_kmsg_free", MACH_IPC_MSG),
		make_pair("MACH_IPC_msg_trap", MACH_IPC_MSG),
		make_pair("MACH_IPC_msg_link", MACH_IPC_MSG),
		make_pair("MACH_IPC_msg_recv", MACH_IPC_MSG),
		make_pair("MACH_IPC_msg_recv_voucher_re", MACH_IPC_MSG),
		make_pair("MACH_IPC_msg_send", MACH_IPC_MSG),
		make_pair("MACH_IPC_msg_boarder", MACH_IPC_MSG),
		make_pair("MACH_IPC_msg_thread_voucher", MACH_IPC_MSG),
		make_pair("MACH_IPC_msg_dump", MACH_IPC_MSG),
		make_pair("MACH_IPC_msg_dsc", MACH_IPC_MSG),
		make_pair("MACH_IPC_msg_idsc", MACH_IPC_MSG),
		make_pair("MACH_IPC_voucher_info", MACH_IPC_VOUCHER_INFO),
		make_pair("MACH_IPC_voucher_conn", MACH_IPC_VOUCHER_CONN),
		make_pair("MACH_IPC_voucher_reuse", MACH_IPC_VOUCHER_TRANSIT),
		make_pair("MACH_IPC_voucher_create", MACH_IPC_VOUCHER_TRANSIT),
		make_pair("MACH_IPC_voucher_remove", MACH_IPC_VOUCHER_DEALLOC),
		make_pair("MACH_IPC_voucher_destroy", MACH_IPC_VOUCHER_DEALLOC),
		make_pair("Bank_Account_redeem", MACH_BANK_ACCOUNT),
	//	make_pair("Bank_Account_settle", MACH_BANK_ACCOUNT),
		make_pair("MACH_MKRUNNABLE", MACH_MK_RUN),
		make_pair("MACH_WAKEUP_REASON", MACH_MK_RUN),
		make_pair("INTERRUPT", INTR),
		make_pair("wq__run_nextitem", WQ_NEXT),
		make_pair("MACH_TS_MAINTENANCE", MACH_TS),
		make_pair("MACH_WAIT", MACH_WAIT),
		make_pair("MACH_WAIT_REASON", MACH_WAIT),
		make_pair("dispatch_enqueue", DISP_ENQ),
		make_pair("dispatch_dequeue", DISP_DEQ),
		make_pair("dispatch_execute", DISP_EXE),
		make_pair("MACH_CALLCREATE", MACH_CALLCREATE),
		make_pair("MACH_CALLOUT", MACH_CALLOUT),
		make_pair("MACH_CALLCANCEL", MACH_CALLCANCEL),
		make_pair("MSG_Pathinfo", BACKTRACE),
		make_pair("MSG_Backtrace", BACKTRACE),
		make_pair("MACH_SYSCALL", MACH_SYS),
		make_pair("BSD_SYSCALL", BSD_SYS),
		make_pair("CALayerSet", CA_SET),
		make_pair("NSViewSet", CA_SET),
		make_pair("CALayerDisplay", CA_DISPLAY),
		make_pair("HWBR_trap", BREAKPOINT_TRAP),
		make_pair("RL_Observer", RL_OBSERVER),
		make_pair("EventRef", EVENTREF),
		make_pair("NSAppGetEvent", NSAPPEVENT),
		make_pair("NSEvent", NSAPPEVENT),
		make_pair("dispatch_mig_server", DISP_MIG)
	};
}
